notifications:
  email: false
  irc:
    channels:
      - "irc.mysociety.org#sayit"
    use_notice: true

sudo: false

language: python

services:
  - elasticsearch

env:
  global:
    - CFLAGS="-O0"
  matrix:
    - TOXENV=flake8
    - TOXENV=py27-1.8
    - TOXENV=py27-1.9
    - TOXENV=py27-1.10
    - TOXENV=py34-1.8
    - TOXENV=py34-1.9
    - TOXENV=py34-1.10

matrix:
  allow_failures:
    - env: TOXENV=py27-1.10
    - env: TOXENV=py34-1.10

addons:
  firefox: latest
  apt:
    packages:
      - ffmpeg
      - libavcodec-extra-53
      - xvfb

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.12.0/geckodriver-v0.12.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.12.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - pip install tox

before_script:
  - psql -c 'create database "sayit-example-project";' -U postgres
  - export DISPLAY=:99.0
  - 'if [ $TOXENV != "flake8" ]; then sh -e /etc/init.d/xvfb start; fi'

script:
  - tox
